import Link from "next/link";
import { CalendarDays, Clock, Coffee, Dumbbell, Heart, PlayCircle, Wind } from "lucide-react";
import { ExercisePrescription, type PrescribedExercise } from "./ExercisePrescription";
import { ACCENT_HEX } from "@/lib/design/accents";

/**
 * Loose type. Real-world data may be missing fields when generated by an
 * older version of the plan generator. Every access below is defensive.
 */
export type DailyPlan = {
  date?: string;
  day_name?: string;
  type?: "strength" | "cardio_zone2" | "cardio_hiit" | "active_recovery" | "rest" | string;
  focus?: string;
  why_today?: string;
  duration_minutes?: number;
  warmup?: { minutes?: number; instructions?: string[] } | null;
  exercises?: PrescribedExercise[];
  cardio?: { minutes?: number; mode?: string; intensity?: string; why?: string } | null;
  cooldown?: { minutes?: number; instructions?: string[] } | null;
  notes?: string;
};

export function DayCard({
  plan,
  isToday,
  defaultOpen = false,
}: {
  plan: DailyPlan;
  isToday: boolean;
  defaultOpen?: boolean;
}) {
  // A corrupt plan may contain a null/non-object day — skip instead of crashing the whole page.
  if (!plan || typeof plan !== "object") return null;

  const type = plan.type ?? "strength";
  const accent = accentForType(type);
  const exercises = Array.isArray(plan.exercises) ? plan.exercises : [];
  const warmupInstructions = Array.isArray(plan.warmup?.instructions) ? plan.warmup.instructions : [];
  const cooldownInstructions = Array.isArray(plan.cooldown?.instructions) ? plan.cooldown.instructions : [];
  const planDate = plan.date && !Number.isNaN(Date.parse(plan.date + "T00:00:00")) ? plan.date : null;
  const dateLabel = planDate
    ? new Date(planDate + "T00:00:00").toLocaleDateString("en-US", { month: "short", day: "numeric" })
    : "";
  const dayName = plan.day_name ?? "";
  const focus = plan.focus ?? "Training day";
  const whyToday = plan.why_today ?? "";
  const duration = typeof plan.duration_minutes === "number" ? plan.duration_minutes : 0;
  const notes = plan.notes ?? "";

  return (
    <details
      open={defaultOpen}
      className="surface-elevated group rounded-[var(--radius-card)] border bg-surface overflow-hidden"
      style={{ borderColor: isToday ? accent : "var(--color-hairline)" }}
    >
      <summary className="flex cursor-pointer items-center gap-3 p-4 list-none">
        <div
          className="grid size-10 shrink-0 place-items-center rounded-xl"
          style={{ backgroundColor: `${accent}1a`, color: accent }}
        >
          <TypeIcon type={type} className="size-5" />
        </div>
        <div className="flex flex-1 flex-col min-w-0">
          <div className="flex items-center gap-2">
            <p className="text-sm font-semibold">{dayName}</p>
            {isToday && (
              <span
                className="rounded-full px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-wider text-white"
                style={{ backgroundColor: accent }}
              >
                Today
              </span>
            )}
            {dateLabel && <span className="text-[11px] text-text-tertiary">{dateLabel}</span>}
          </div>
          <p className="truncate text-xs text-text-secondary">{focus}</p>
        </div>
        {duration > 0 && (
          <span className="metric flex items-center gap-1 text-xs text-text-tertiary">
            <Clock className="size-3" />
            {duration} min
          </span>
        )}
      </summary>

      <div className="space-y-5 border-t border-hairline px-4 py-4">
        {whyToday && (
          <Block icon={CalendarDays} label="Why today" accent={accent}>
            <p className="text-sm text-text-primary leading-relaxed">{whyToday}</p>
          </Block>
        )}

        {type === "rest" && notes && (
          <Block icon={Coffee} label="What to do" accent={accent}>
            <p className="text-sm leading-relaxed">{notes}</p>
          </Block>
        )}

        {warmupInstructions.length > 0 && (
          <Block
            icon={Wind}
            label={`Warm-up${plan.warmup?.minutes ? ` · ${plan.warmup.minutes} min` : ""}`}
            accent={ACCENT_HEX.recovery}
          >
            <ul className="space-y-1">
              {warmupInstructions.map((line, i) => (
                <li key={i} className="flex gap-2 text-sm text-text-primary">
                  <span className="text-text-tertiary">·</span>
                  <span>{line}</span>
                </li>
              ))}
            </ul>
          </Block>
        )}

        {exercises.length > 0 && (
          <Block icon={Dumbbell} label="Strength block" accent={accent}>
            {planDate && (
              <Link
                href={`/session/${planDate}`}
                className="mb-3 flex items-center justify-center gap-2 rounded-[var(--radius-card)] px-5 py-3 text-sm font-semibold text-white"
                style={{ backgroundColor: accent }}
              >
                <PlayCircle className="size-4" /> Start session
              </Link>
            )}
            <div className="flex flex-col gap-2">
              {exercises.map((ex, i) => (
                <ExercisePrescription key={ex?.exercise_id ?? i} exercise={ex} index={i} />
              ))}
            </div>
          </Block>
        )}

        {plan.cardio && (plan.cardio.mode || plan.cardio.intensity || plan.cardio.minutes) && (
          <Block
            icon={Heart}
            label={`Cardio${plan.cardio.minutes ? ` · ${plan.cardio.minutes} min` : ""}`}
            accent={ACCENT_HEX.workout}
          >
            <div className="rounded-[var(--radius-card)] bg-canvas p-3 space-y-2 text-sm">
              {plan.cardio.mode && (
                <p>
                  <span className="text-text-tertiary">Mode: </span>
                  <span>{plan.cardio.mode}</span>
                </p>
              )}
              {plan.cardio.intensity && (
                <p>
                  <span className="text-text-tertiary">Intensity: </span>
                  <span>{plan.cardio.intensity}</span>
                </p>
              )}
              {plan.cardio.why && (
                <p className="text-xs text-text-secondary leading-relaxed">
                  <span className="text-text-tertiary">Why: </span>
                  {plan.cardio.why}
                </p>
              )}
            </div>
          </Block>
        )}

        {cooldownInstructions.length > 0 && (
          <Block
            icon={Wind}
            label={`Cooldown${plan.cooldown?.minutes ? ` · ${plan.cooldown.minutes} min` : ""}`}
            accent={ACCENT_HEX.recovery}
          >
            <ul className="space-y-1">
              {cooldownInstructions.map((line, i) => (
                <li key={i} className="flex gap-2 text-sm text-text-primary">
                  <span className="text-text-tertiary">·</span>
                  <span>{line}</span>
                </li>
              ))}
            </ul>
          </Block>
        )}

        {notes && type !== "rest" && (
          <p className="rounded-[var(--radius-card)] border border-hairline bg-canvas p-3 text-xs text-text-secondary leading-relaxed">
            <strong className="text-text-primary">Coach note: </strong>{notes}
          </p>
        )}
      </div>
    </details>
  );
}

function Block({
  icon: Icon,
  label,
  accent,
  children,
}: {
  icon: typeof CalendarDays;
  label: string;
  accent: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className="mb-2 flex items-center gap-1.5">
        <Icon className="size-3" style={{ color: accent }} strokeWidth={2.5} />
        <span className="text-[10px] uppercase tracking-wider" style={{ color: accent }}>
          {label}
        </span>
      </div>
      {children}
    </div>
  );
}

function accentForType(type: string): string {
  switch (type) {
    case "strength":
      return ACCENT_HEX.workout;
    case "cardio_zone2":
    case "cardio_hiit":
      return ACCENT_HEX.energy;
    case "active_recovery":
      return ACCENT_HEX.recovery;
    case "rest":
      return ACCENT_HEX.sleep;
    default:
      // Never return undefined — would crash <Icon/> rendering
      return ACCENT_HEX.workout;
  }
}

function TypeIcon({ type, className }: { type: string; className?: string }) {
  switch (type) {
    case "cardio_zone2":
    case "cardio_hiit":
      return <Heart className={className} />;
    case "active_recovery":
      return <Wind className={className} />;
    case "rest":
      return <Coffee className={className} />;
    default:
      return <Dumbbell className={className} />;
  }
}
